language: java
jdk:
  #  - oraclejdk8
  #  - oraclejdk9
  #  - oraclejdk11
  - openjdk11
  - openjdk-ea
  - openjdk8
#jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache
    - $HOME/.cache
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "jukusoft"

#don't do a shallow clone (for sonarqube)
git:
  depth: 9999999

script:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - JAVA_VER=$(java -version 2>&1 | sed -n ';s/.* version "\(.*\)\.\(.*\)\..*"/\1\2/p;')
  - echo JAVA_VER
#  - [ "$JAVA_VER" -e 18 ] && mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=${SONAR_TOKEN} || echo "Don't execute sonarqube, because it's not openjdk8"
  - mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=${SONAR_TOKEN}

notifications:
  email: false